[tool.poetry]
name = "crew-agents"
version = "0.1.0"
description = "This is a crewai test for practice"
authors = ["Ossie Bodero"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
